### ISSUE TITLE
当时间到 config.json 中的 ”开始时间时 程序会崩溃

### ISSUE THREAD

**Issue by dfh3913** [DuguSand/class_form#1]
Traceback (most recent call last):
  File "C:\Users\\Desktop\class_form-main\class_form.py", line 332, in <module>
    cl.find()
  File "C:\Users\\Desktop\class_form-main\class_form.py", line 322, in find
    self.onclass()
  File "C:\Users\\Desktop\class_form-main\class_form.py", line 224, in onclass
    self.move([self.window,self.offtk[0]],[self.width,1],[self.height,self.y*2+self.offtk[1].winfo_reqheight()],[self.xroot,int((self.window.winfo_screenwidth()+self.width)/2)-self.x+20],[self.yroot,self.yroot])
TypeError: 'NoneType' object is not subscriptable
>>>

**Comment by DuguSand** [comment]
之前有人跟我说过，改过了

**Comment by PANDAJSR** [comment]
请使用classisland，其使用dotnet编写，且功能很强大

**Comment by dfh3913** [comment]
> 之前有人跟我说过，改过了

偶然发现我的报错里让我实名上网了，，哥们方便帮我把这个issue关了或者删了吗
